service: midlandbookshop-service

provider:
  name: aws
  runtime: java8
  profile: admin@megafasteners.com
  region: us-east-2
  timeout: 60
  memorySize: 1024
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        - 'arn:aws:s3:::${self:custom.myBucket}/*'
    - Effect: 'Allow'
      Action:
        - 'sns:Publish'
      Resource:
        - 'arn:aws:sns:us-east-2:143180287861:Inbound-Books'
        

custom:
  myBucket: midland-releases
package:
  artifact: target/midlandbookshop-service.jar

functions:

  simpleEventTrigger:
    handler: com.maintainapps.midlandbookshop.BookHandler

