//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 02:03:50 PM GST 
//


package com.maintainapps.schema.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}LevelSequenceNumber" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}TextItem"/>
 *           &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}AVItem"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}ComponentTypeName"/>
 *             &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}ComponentNumber" minOccurs="0"/>
 *             &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}TitleDetail" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}ComponentNumber" minOccurs="0"/>
 *             &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}TitleDetail" maxOccurs="unbounded"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;group ref="{http://ns.editeur.org/onix/3.0/reference}gp.authorship"/>
 *         &lt;group ref="{http://ns.editeur.org/onix/3.0/reference}gp.languages"/>
 *         &lt;group ref="{http://ns.editeur.org/onix/3.0/reference}gp.subjects"/>
 *         &lt;group ref="{http://ns.editeur.org/onix/3.0/reference}gp.descriptions"/>
 *         &lt;group ref="{http://ns.editeur.org/onix/3.0/reference}gp.related_materials"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://ns.editeur.org/onix/3.0/reference}generalAttributes"/>
 *       &lt;attribute name="refname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="ContentItem"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="shortname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="contentitem"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "ContentItem")
public class ContentItem {

    @XmlElementRefs({
        @XmlElementRef(name = "Language", namespace = "http://ns.editeur.org/onix/3.0/reference", type = Language.class, required = false),
        @XmlElementRef(name = "CitedContent", namespace = "http://ns.editeur.org/onix/3.0/reference", type = CitedContent.class, required = false),
        @XmlElementRef(name = "ComponentNumber", namespace = "http://ns.editeur.org/onix/3.0/reference", type = ComponentNumber.class, required = false),
        @XmlElementRef(name = "TextItem", namespace = "http://ns.editeur.org/onix/3.0/reference", type = TextItem.class, required = false),
        @XmlElementRef(name = "TextContent", namespace = "http://ns.editeur.org/onix/3.0/reference", type = TextContent.class, required = false),
        @XmlElementRef(name = "Contributor", namespace = "http://ns.editeur.org/onix/3.0/reference", type = Contributor.class, required = false),
        @XmlElementRef(name = "NoContributor", namespace = "http://ns.editeur.org/onix/3.0/reference", type = NoContributor.class, required = false),
        @XmlElementRef(name = "ComponentTypeName", namespace = "http://ns.editeur.org/onix/3.0/reference", type = ComponentTypeName.class, required = false),
        @XmlElementRef(name = "ContributorStatement", namespace = "http://ns.editeur.org/onix/3.0/reference", type = ContributorStatement.class, required = false),
        @XmlElementRef(name = "RelatedWork", namespace = "http://ns.editeur.org/onix/3.0/reference", type = RelatedWork.class, required = false),
        @XmlElementRef(name = "AVItem", namespace = "http://ns.editeur.org/onix/3.0/reference", type = AVItem.class, required = false),
        @XmlElementRef(name = "RelatedProduct", namespace = "http://ns.editeur.org/onix/3.0/reference", type = RelatedProduct.class, required = false),
        @XmlElementRef(name = "Subject", namespace = "http://ns.editeur.org/onix/3.0/reference", type = Subject.class, required = false),
        @XmlElementRef(name = "TitleDetail", namespace = "http://ns.editeur.org/onix/3.0/reference", type = TitleDetail.class, required = false),
        @XmlElementRef(name = "NameAsSubject", namespace = "http://ns.editeur.org/onix/3.0/reference", type = NameAsSubject.class, required = false),
        @XmlElementRef(name = "SupportingResource", namespace = "http://ns.editeur.org/onix/3.0/reference", type = SupportingResource.class, required = false),
        @XmlElementRef(name = "LevelSequenceNumber", namespace = "http://ns.editeur.org/onix/3.0/reference", type = LevelSequenceNumber.class, required = false)
    })
    protected List<Object> content;
    @XmlAttribute(name = "refname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refname;
    @XmlAttribute(name = "shortname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String shortname;
    @XmlAttribute(name = "datestamp")
    protected String datestamp;
    @XmlAttribute(name = "sourcetype")
    protected String sourcetype;
    @XmlAttribute(name = "sourcename")
    protected String sourcename;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "ComponentNumber" is used by two different parts of a schema. See: 
     * line 3464 of file:/C:/Lumine/workspace-spring/book-service/schema/ONIX_BookProduct_3.0_reference.xsd
     * line 3460 of file:/C:/Lumine/workspace-spring/book-service/schema/ONIX_BookProduct_3.0_reference.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Language }
     * {@link CitedContent }
     * {@link ComponentNumber }
     * {@link TextItem }
     * {@link TextContent }
     * {@link Contributor }
     * {@link NoContributor }
     * {@link ComponentTypeName }
     * {@link ContributorStatement }
     * {@link RelatedWork }
     * {@link AVItem }
     * {@link RelatedProduct }
     * {@link Subject }
     * {@link TitleDetail }
     * {@link NameAsSubject }
     * {@link SupportingResource }
     * {@link LevelSequenceNumber }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the refname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefname() {
        return refname;
    }

    /**
     * Sets the value of the refname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefname(String value) {
        this.refname = value;
    }

    /**
     * Gets the value of the shortname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortname(String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the datestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatestamp() {
        return datestamp;
    }

    /**
     * Sets the value of the datestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatestamp(String value) {
        this.datestamp = value;
    }

    /**
     * Gets the value of the sourcetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcetype() {
        return sourcetype;
    }

    /**
     * Sets the value of the sourcetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcetype(String value) {
        this.sourcetype = value;
    }

    /**
     * Gets the value of the sourcename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcename() {
        return sourcename;
    }

    /**
     * Sets the value of the sourcename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcename(String value) {
        this.sourcename = value;
    }

}
