//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 02:03:50 PM GST 
//


package com.maintainapps.schema.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}SequenceNumber" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}SalesOutlet" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;group ref="{http://ns.editeur.org/onix/3.0/reference}gp.resource_specification"/>
 *           &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}NoResource"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://ns.editeur.org/onix/3.0/reference}generalAttributes"/>
 *       &lt;attribute name="refname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="CoverResource"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="shortname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="coverresource"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sequenceNumber",
    "salesOutlet",
    "resourceIdentifier",
    "resourceRole",
    "resourceFileDetail",
    "resourceFileFeature",
    "resourceFileDescription",
    "resourceFileContentDescription",
    "resourceFileLink",
    "resourceFileDate",
    "noResource"
})
@XmlRootElement(name = "CoverResource")
public class CoverResource {

    @XmlElement(name = "SequenceNumber")
    protected SequenceNumber sequenceNumber;
    @XmlElement(name = "SalesOutlet")
    protected List<SalesOutlet> salesOutlet;
    @XmlElement(name = "ResourceIdentifier")
    protected List<ResourceIdentifier> resourceIdentifier;
    @XmlElement(name = "ResourceRole")
    protected ResourceRole resourceRole;
    @XmlElement(name = "ResourceFileDetail")
    protected List<ResourceFileDetail> resourceFileDetail;
    @XmlElement(name = "ResourceFileFeature")
    protected List<ResourceFileFeature> resourceFileFeature;
    @XmlElement(name = "ResourceFileDescription")
    protected List<ResourceFileDescription> resourceFileDescription;
    @XmlElement(name = "ResourceFileContentDescription")
    protected List<ResourceFileContentDescription> resourceFileContentDescription;
    @XmlElement(name = "ResourceFileLink")
    protected List<ResourceFileLink> resourceFileLink;
    @XmlElement(name = "ResourceFileDate")
    protected List<ResourceFileDate> resourceFileDate;
    @XmlElement(name = "NoResource")
    protected NoResource noResource;
    @XmlAttribute(name = "refname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refname;
    @XmlAttribute(name = "shortname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String shortname;
    @XmlAttribute(name = "datestamp")
    protected String datestamp;
    @XmlAttribute(name = "sourcetype")
    protected String sourcetype;
    @XmlAttribute(name = "sourcename")
    protected String sourcename;

    /**
     * Gets the value of the sequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link SequenceNumber }
     *     
     */
    public SequenceNumber getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Sets the value of the sequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link SequenceNumber }
     *     
     */
    public void setSequenceNumber(SequenceNumber value) {
        this.sequenceNumber = value;
    }

    /**
     * Gets the value of the salesOutlet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the salesOutlet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSalesOutlet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SalesOutlet }
     * 
     * 
     */
    public List<SalesOutlet> getSalesOutlet() {
        if (salesOutlet == null) {
            salesOutlet = new ArrayList<SalesOutlet>();
        }
        return this.salesOutlet;
    }

    /**
     * Gets the value of the resourceIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resourceIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResourceIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResourceIdentifier }
     * 
     * 
     */
    public List<ResourceIdentifier> getResourceIdentifier() {
        if (resourceIdentifier == null) {
            resourceIdentifier = new ArrayList<ResourceIdentifier>();
        }
        return this.resourceIdentifier;
    }

    /**
     * Gets the value of the resourceRole property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceRole }
     *     
     */
    public ResourceRole getResourceRole() {
        return resourceRole;
    }

    /**
     * Sets the value of the resourceRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceRole }
     *     
     */
    public void setResourceRole(ResourceRole value) {
        this.resourceRole = value;
    }

    /**
     * Gets the value of the resourceFileDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resourceFileDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResourceFileDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResourceFileDetail }
     * 
     * 
     */
    public List<ResourceFileDetail> getResourceFileDetail() {
        if (resourceFileDetail == null) {
            resourceFileDetail = new ArrayList<ResourceFileDetail>();
        }
        return this.resourceFileDetail;
    }

    /**
     * Gets the value of the resourceFileFeature property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resourceFileFeature property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResourceFileFeature().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResourceFileFeature }
     * 
     * 
     */
    public List<ResourceFileFeature> getResourceFileFeature() {
        if (resourceFileFeature == null) {
            resourceFileFeature = new ArrayList<ResourceFileFeature>();
        }
        return this.resourceFileFeature;
    }

    /**
     * Gets the value of the resourceFileDescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resourceFileDescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResourceFileDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResourceFileDescription }
     * 
     * 
     */
    public List<ResourceFileDescription> getResourceFileDescription() {
        if (resourceFileDescription == null) {
            resourceFileDescription = new ArrayList<ResourceFileDescription>();
        }
        return this.resourceFileDescription;
    }

    /**
     * Gets the value of the resourceFileContentDescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resourceFileContentDescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResourceFileContentDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResourceFileContentDescription }
     * 
     * 
     */
    public List<ResourceFileContentDescription> getResourceFileContentDescription() {
        if (resourceFileContentDescription == null) {
            resourceFileContentDescription = new ArrayList<ResourceFileContentDescription>();
        }
        return this.resourceFileContentDescription;
    }

    /**
     * Gets the value of the resourceFileLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resourceFileLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResourceFileLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResourceFileLink }
     * 
     * 
     */
    public List<ResourceFileLink> getResourceFileLink() {
        if (resourceFileLink == null) {
            resourceFileLink = new ArrayList<ResourceFileLink>();
        }
        return this.resourceFileLink;
    }

    /**
     * Gets the value of the resourceFileDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resourceFileDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResourceFileDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResourceFileDate }
     * 
     * 
     */
    public List<ResourceFileDate> getResourceFileDate() {
        if (resourceFileDate == null) {
            resourceFileDate = new ArrayList<ResourceFileDate>();
        }
        return this.resourceFileDate;
    }

    /**
     * Gets the value of the noResource property.
     * 
     * @return
     *     possible object is
     *     {@link NoResource }
     *     
     */
    public NoResource getNoResource() {
        return noResource;
    }

    /**
     * Sets the value of the noResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoResource }
     *     
     */
    public void setNoResource(NoResource value) {
        this.noResource = value;
    }

    /**
     * Gets the value of the refname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefname() {
        return refname;
    }

    /**
     * Sets the value of the refname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefname(String value) {
        this.refname = value;
    }

    /**
     * Gets the value of the shortname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortname(String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the datestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatestamp() {
        return datestamp;
    }

    /**
     * Sets the value of the datestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatestamp(String value) {
        this.datestamp = value;
    }

    /**
     * Gets the value of the sourcetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcetype() {
        return sourcetype;
    }

    /**
     * Sets the value of the sourcetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcetype(String value) {
        this.sourcetype = value;
    }

    /**
     * Gets the value of the sourcename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcename() {
        return sourcename;
    }

    /**
     * Sets the value of the sourcename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcename(String value) {
        this.sourcename = value;
    }

}
