//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 02:03:50 PM GST 
//


package com.maintainapps.schema.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List121.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="List121">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Adlm"/>
 *     &lt;enumeration value="Afak"/>
 *     &lt;enumeration value="Aghb"/>
 *     &lt;enumeration value="Ahom"/>
 *     &lt;enumeration value="Arab"/>
 *     &lt;enumeration value="Aran"/>
 *     &lt;enumeration value="Armi"/>
 *     &lt;enumeration value="Armn"/>
 *     &lt;enumeration value="Avst"/>
 *     &lt;enumeration value="Bali"/>
 *     &lt;enumeration value="Bamu"/>
 *     &lt;enumeration value="Bass"/>
 *     &lt;enumeration value="Batk"/>
 *     &lt;enumeration value="Beng"/>
 *     &lt;enumeration value="Bhks"/>
 *     &lt;enumeration value="Blis"/>
 *     &lt;enumeration value="Bopo"/>
 *     &lt;enumeration value="Brah"/>
 *     &lt;enumeration value="Brai"/>
 *     &lt;enumeration value="Bugi"/>
 *     &lt;enumeration value="Buhd"/>
 *     &lt;enumeration value="Cakm"/>
 *     &lt;enumeration value="Cans"/>
 *     &lt;enumeration value="Cari"/>
 *     &lt;enumeration value="Cham"/>
 *     &lt;enumeration value="Cher"/>
 *     &lt;enumeration value="Cirt"/>
 *     &lt;enumeration value="Copt"/>
 *     &lt;enumeration value="Cprt"/>
 *     &lt;enumeration value="Cyrl"/>
 *     &lt;enumeration value="Cyrs"/>
 *     &lt;enumeration value="Deva"/>
 *     &lt;enumeration value="Dogr"/>
 *     &lt;enumeration value="Dsrt"/>
 *     &lt;enumeration value="Dupl"/>
 *     &lt;enumeration value="Egyd"/>
 *     &lt;enumeration value="Egyh"/>
 *     &lt;enumeration value="Egyp"/>
 *     &lt;enumeration value="Elba"/>
 *     &lt;enumeration value="Ethi"/>
 *     &lt;enumeration value="Geok"/>
 *     &lt;enumeration value="Geor"/>
 *     &lt;enumeration value="Glag"/>
 *     &lt;enumeration value="Gong"/>
 *     &lt;enumeration value="Gonm"/>
 *     &lt;enumeration value="Goth"/>
 *     &lt;enumeration value="Gran"/>
 *     &lt;enumeration value="Grek"/>
 *     &lt;enumeration value="Gujr"/>
 *     &lt;enumeration value="Guru"/>
 *     &lt;enumeration value="Hanb"/>
 *     &lt;enumeration value="Hang"/>
 *     &lt;enumeration value="Hani"/>
 *     &lt;enumeration value="Hano"/>
 *     &lt;enumeration value="Hans"/>
 *     &lt;enumeration value="Hant"/>
 *     &lt;enumeration value="Hatr"/>
 *     &lt;enumeration value="Hebr"/>
 *     &lt;enumeration value="Hira"/>
 *     &lt;enumeration value="Hluw"/>
 *     &lt;enumeration value="Hmng"/>
 *     &lt;enumeration value="Hrkt"/>
 *     &lt;enumeration value="Hung"/>
 *     &lt;enumeration value="Inds"/>
 *     &lt;enumeration value="Ital"/>
 *     &lt;enumeration value="Jamo"/>
 *     &lt;enumeration value="Java"/>
 *     &lt;enumeration value="Jpan"/>
 *     &lt;enumeration value="Jurc"/>
 *     &lt;enumeration value="Kali"/>
 *     &lt;enumeration value="Kana"/>
 *     &lt;enumeration value="Khar"/>
 *     &lt;enumeration value="Khmr"/>
 *     &lt;enumeration value="Khoj"/>
 *     &lt;enumeration value="Kitl"/>
 *     &lt;enumeration value="Kits"/>
 *     &lt;enumeration value="Knda"/>
 *     &lt;enumeration value="Kore"/>
 *     &lt;enumeration value="Kpel"/>
 *     &lt;enumeration value="Kthi"/>
 *     &lt;enumeration value="Lana"/>
 *     &lt;enumeration value="Laoo"/>
 *     &lt;enumeration value="Latf"/>
 *     &lt;enumeration value="Latg"/>
 *     &lt;enumeration value="Latn"/>
 *     &lt;enumeration value="Leke"/>
 *     &lt;enumeration value="Lepc"/>
 *     &lt;enumeration value="Limb"/>
 *     &lt;enumeration value="Lina"/>
 *     &lt;enumeration value="Linb"/>
 *     &lt;enumeration value="Lisu"/>
 *     &lt;enumeration value="Loma"/>
 *     &lt;enumeration value="Lyci"/>
 *     &lt;enumeration value="Lydi"/>
 *     &lt;enumeration value="Mahj"/>
 *     &lt;enumeration value="Maka"/>
 *     &lt;enumeration value="Mand"/>
 *     &lt;enumeration value="Mani"/>
 *     &lt;enumeration value="Marc"/>
 *     &lt;enumeration value="Maya"/>
 *     &lt;enumeration value="Medf"/>
 *     &lt;enumeration value="Mend"/>
 *     &lt;enumeration value="Merc"/>
 *     &lt;enumeration value="Mero"/>
 *     &lt;enumeration value="Mlym"/>
 *     &lt;enumeration value="Modi"/>
 *     &lt;enumeration value="Mong"/>
 *     &lt;enumeration value="Moon"/>
 *     &lt;enumeration value="Mroo"/>
 *     &lt;enumeration value="Mtei"/>
 *     &lt;enumeration value="Mult"/>
 *     &lt;enumeration value="Mymr"/>
 *     &lt;enumeration value="Narb"/>
 *     &lt;enumeration value="Nbat"/>
 *     &lt;enumeration value="Newa"/>
 *     &lt;enumeration value="Nkgb"/>
 *     &lt;enumeration value="Nkoo"/>
 *     &lt;enumeration value="Nshu"/>
 *     &lt;enumeration value="Ogam"/>
 *     &lt;enumeration value="Olck"/>
 *     &lt;enumeration value="Orkh"/>
 *     &lt;enumeration value="Orya"/>
 *     &lt;enumeration value="Osge"/>
 *     &lt;enumeration value="Osma"/>
 *     &lt;enumeration value="Palm"/>
 *     &lt;enumeration value="Pauc"/>
 *     &lt;enumeration value="Perm"/>
 *     &lt;enumeration value="Phag"/>
 *     &lt;enumeration value="Phli"/>
 *     &lt;enumeration value="Phlp"/>
 *     &lt;enumeration value="Phlv"/>
 *     &lt;enumeration value="Phnx"/>
 *     &lt;enumeration value="Plrd"/>
 *     &lt;enumeration value="Piqd"/>
 *     &lt;enumeration value="Prti"/>
 *     &lt;enumeration value="Qaaa"/>
 *     &lt;enumeration value="Qabx"/>
 *     &lt;enumeration value="Rjng"/>
 *     &lt;enumeration value="Roro"/>
 *     &lt;enumeration value="Runr"/>
 *     &lt;enumeration value="Samr"/>
 *     &lt;enumeration value="Sara"/>
 *     &lt;enumeration value="Sarb"/>
 *     &lt;enumeration value="Saur"/>
 *     &lt;enumeration value="Sgnw"/>
 *     &lt;enumeration value="Shaw"/>
 *     &lt;enumeration value="Shrd"/>
 *     &lt;enumeration value="Sidd"/>
 *     &lt;enumeration value="Sind"/>
 *     &lt;enumeration value="Sinh"/>
 *     &lt;enumeration value="Sora"/>
 *     &lt;enumeration value="Soyo"/>
 *     &lt;enumeration value="Sund"/>
 *     &lt;enumeration value="Sylo"/>
 *     &lt;enumeration value="Syrc"/>
 *     &lt;enumeration value="Syre"/>
 *     &lt;enumeration value="Syrj"/>
 *     &lt;enumeration value="Syrn"/>
 *     &lt;enumeration value="Tagb"/>
 *     &lt;enumeration value="Takr"/>
 *     &lt;enumeration value="Tale"/>
 *     &lt;enumeration value="Talu"/>
 *     &lt;enumeration value="Taml"/>
 *     &lt;enumeration value="Tang"/>
 *     &lt;enumeration value="Tavt"/>
 *     &lt;enumeration value="Telu"/>
 *     &lt;enumeration value="Teng"/>
 *     &lt;enumeration value="Tfng"/>
 *     &lt;enumeration value="Tglg"/>
 *     &lt;enumeration value="Thaa"/>
 *     &lt;enumeration value="Thai"/>
 *     &lt;enumeration value="Tibt"/>
 *     &lt;enumeration value="Tirh"/>
 *     &lt;enumeration value="Ugar"/>
 *     &lt;enumeration value="Vaii"/>
 *     &lt;enumeration value="Visp"/>
 *     &lt;enumeration value="Wara"/>
 *     &lt;enumeration value="Wole"/>
 *     &lt;enumeration value="Xpeo"/>
 *     &lt;enumeration value="Xsux"/>
 *     &lt;enumeration value="Yiii"/>
 *     &lt;enumeration value="Zanb"/>
 *     &lt;enumeration value="Zinh"/>
 *     &lt;enumeration value="Zmth"/>
 *     &lt;enumeration value="Zsye"/>
 *     &lt;enumeration value="Zsym"/>
 *     &lt;enumeration value="Zxxx"/>
 *     &lt;enumeration value="Zyyy"/>
 *     &lt;enumeration value="Zzzz"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "List121")
@XmlEnum
public enum List121 {


    /**
     * For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Adlm")
    ADLM("Adlm"),

    /**
     * Script is not supported by Unicode
     * 
     */
    @XmlEnumValue("Afak")
    AFAK("Afak"),

    /**
     * Ancient/historic script. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Aghb")
    AGHB("Aghb"),

    /**
     * Ancient/historic script. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Ahom")
    AHOM("Ahom"),
    @XmlEnumValue("Arab")
    ARAB("Arab"),

    /**
     * Typographic variant of Arabic. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Aran")
    ARAN("Aran"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Armi")
    ARMI("Armi"),
    @XmlEnumValue("Armn")
    ARMN("Armn"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Avst")
    AVST("Avst"),
    @XmlEnumValue("Bali")
    BALI("Bali"),
    @XmlEnumValue("Bamu")
    BAMU("Bamu"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Bass")
    BASS("Bass"),
    @XmlEnumValue("Batk")
    BATK("Batk"),
    @XmlEnumValue("Beng")
    BENG("Beng"),

    /**
     * Ancient/historic script. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Bhks")
    BHKS("Bhks"),

    /**
     * Script is not supported by Unicode
     * 
     */
    @XmlEnumValue("Blis")
    BLIS("Blis"),
    @XmlEnumValue("Bopo")
    BOPO("Bopo"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Brah")
    BRAH("Brah"),
    @XmlEnumValue("Brai")
    BRAI("Brai"),
    @XmlEnumValue("Bugi")
    BUGI("Bugi"),
    @XmlEnumValue("Buhd")
    BUHD("Buhd"),
    @XmlEnumValue("Cakm")
    CAKM("Cakm"),
    @XmlEnumValue("Cans")
    CANS("Cans"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Cari")
    CARI("Cari"),
    @XmlEnumValue("Cham")
    CHAM("Cham"),
    @XmlEnumValue("Cher")
    CHER("Cher"),

    /**
     * Script is not supported by Unicode
     * 
     */
    @XmlEnumValue("Cirt")
    CIRT("Cirt"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Copt")
    COPT("Copt"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Cprt")
    CPRT("Cprt"),
    @XmlEnumValue("Cyrl")
    CYRL("Cyrl"),

    /**
     * Ancient/historic, typographic variant of Cyrillic
     * 
     */
    @XmlEnumValue("Cyrs")
    CYRS("Cyrs"),
    @XmlEnumValue("Deva")
    DEVA("Deva"),

    /**
     * Script is not supported by Unicode. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Dogr")
    DOGR("Dogr"),
    @XmlEnumValue("Dsrt")
    DSRT("Dsrt"),
    @XmlEnumValue("Dupl")
    DUPL("Dupl"),

    /**
     * Script is not supported by Unicode
     * 
     */
    @XmlEnumValue("Egyd")
    EGYD("Egyd"),

    /**
     * Script is not supported by Unicode
     * 
     */
    @XmlEnumValue("Egyh")
    EGYH("Egyh"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Egyp")
    EGYP("Egyp"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Elba")
    ELBA("Elba"),
    @XmlEnumValue("Ethi")
    ETHI("Ethi"),

    /**
     * Georgian in Unicode
     * 
     */
    @XmlEnumValue("Geok")
    GEOK("Geok"),
    @XmlEnumValue("Geor")
    GEOR("Geor"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Glag")
    GLAG("Glag"),

    /**
     * Script is not supported by Unicode. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Gong")
    GONG("Gong"),

    /**
     * For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Gonm")
    GONM("Gonm"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Goth")
    GOTH("Goth"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Gran")
    GRAN("Gran"),
    @XmlEnumValue("Grek")
    GREK("Grek"),
    @XmlEnumValue("Gujr")
    GUJR("Gujr"),
    @XmlEnumValue("Guru")
    GURU("Guru"),

    /**
     * See Hani, Bopo. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Hanb")
    HANB("Hanb"),
    @XmlEnumValue("Hang")
    HANG("Hang"),
    @XmlEnumValue("Hani")
    HANI("Hani"),
    @XmlEnumValue("Hano")
    HANO("Hano"),

    /**
     * Subset of Hani
     * 
     */
    @XmlEnumValue("Hans")
    HANS("Hans"),

    /**
     * Subset of Hani
     * 
     */
    @XmlEnumValue("Hant")
    HANT("Hant"),

    /**
     * Ancient/historic script. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Hatr")
    HATR("Hatr"),
    @XmlEnumValue("Hebr")
    HEBR("Hebr"),
    @XmlEnumValue("Hira")
    HIRA("Hira"),

    /**
     * Ancient/historic script. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Hluw")
    HLUW("Hluw"),
    @XmlEnumValue("Hmng")
    HMNG("Hmng"),

    /**
     * See Hira, Kana
     * 
     */
    @XmlEnumValue("Hrkt")
    HRKT("Hrkt"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Hung")
    HUNG("Hung"),

    /**
     * Script is not supported by Unicode
     * 
     */
    @XmlEnumValue("Inds")
    INDS("Inds"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Ital")
    ITAL("Ital"),

    /**
     * Subset of Hang. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Jamo")
    JAMO("Jamo"),
    @XmlEnumValue("Java")
    JAVA("Java"),

    /**
     * See Hani, Hira and Kana
     * 
     */
    @XmlEnumValue("Jpan")
    JPAN("Jpan"),

    /**
     * Script is not supported by Unicode
     * 
     */
    @XmlEnumValue("Jurc")
    JURC("Jurc"),
    @XmlEnumValue("Kali")
    KALI("Kali"),
    @XmlEnumValue("Kana")
    KANA("Kana"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Khar")
    KHAR("Khar"),
    @XmlEnumValue("Khmr")
    KHMR("Khmr"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Khoj")
    KHOJ("Khoj"),

    /**
     * Script is not supported by Unicode. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Kitl")
    KITL("Kitl"),

    /**
     * Script is not supported by Unicode. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Kits")
    KITS("Kits"),
    @XmlEnumValue("Knda")
    KNDA("Knda"),

    /**
     * See Hani and Hang
     * 
     */
    @XmlEnumValue("Kore")
    KORE("Kore"),

    /**
     * Script is not supported by Unicode
     * 
     */
    @XmlEnumValue("Kpel")
    KPEL("Kpel"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Kthi")
    KTHI("Kthi"),
    @XmlEnumValue("Lana")
    LANA("Lana"),
    @XmlEnumValue("Laoo")
    LAOO("Laoo"),

    /**
     * Typographic variant of Latin
     * 
     */
    @XmlEnumValue("Latf")
    LATF("Latf"),

    /**
     * Typographic variant of Latin
     * 
     */
    @XmlEnumValue("Latg")
    LATG("Latg"),
    @XmlEnumValue("Latn")
    LATN("Latn"),

    /**
     * Script is not supported by Unicode. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Leke")
    LEKE("Leke"),
    @XmlEnumValue("Lepc")
    LEPC("Lepc"),
    @XmlEnumValue("Limb")
    LIMB("Limb"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Lina")
    LINA("Lina"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Linb")
    LINB("Linb"),
    @XmlEnumValue("Lisu")
    LISU("Lisu"),

    /**
     * Script is not supported by Unicode
     * 
     */
    @XmlEnumValue("Loma")
    LOMA("Loma"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Lyci")
    LYCI("Lyci"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Lydi")
    LYDI("Lydi"),

    /**
     * Ancient/historic script. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Mahj")
    MAHJ("Mahj"),

    /**
     * Script is not supported by Unicode. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Maka")
    MAKA("Maka"),
    @XmlEnumValue("Mand")
    MAND("Mand"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Mani")
    MANI("Mani"),

    /**
     * Ancient/historic script. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Marc")
    MARC("Marc"),

    /**
     * Script is not supported by Unicode
     * 
     */
    @XmlEnumValue("Maya")
    MAYA("Maya"),

    /**
     * Script is not supported by Unicode. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Medf")
    MEDF("Medf"),
    @XmlEnumValue("Mend")
    MEND("Mend"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Merc")
    MERC("Merc"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Mero")
    MERO("Mero"),
    @XmlEnumValue("Mlym")
    MLYM("Mlym"),

    /**
     * Ancient/historic script. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Modi")
    MODI("Modi"),

    /**
     * Includes Clear, Manchu scripts
     * 
     */
    @XmlEnumValue("Mong")
    MONG("Mong"),

    /**
     * Script is not supported by Unicode
     * 
     */
    @XmlEnumValue("Moon")
    MOON("Moon"),
    @XmlEnumValue("Mroo")
    MROO("Mroo"),
    @XmlEnumValue("Mtei")
    MTEI("Mtei"),

    /**
     * Ancient/historic script. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Mult")
    MULT("Mult"),
    @XmlEnumValue("Mymr")
    MYMR("Mymr"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Narb")
    NARB("Narb"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Nbat")
    NBAT("Nbat"),

    /**
     * For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Newa")
    NEWA("Newa"),

    /**
     * Script is not supported by Unicode
     * 
     */
    @XmlEnumValue("Nkgb")
    NKGB("Nkgb"),
    @XmlEnumValue("Nkoo")
    NKOO("Nkoo"),
    @XmlEnumValue("Nshu")
    NSHU("Nshu"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Ogam")
    OGAM("Ogam"),
    @XmlEnumValue("Olck")
    OLCK("Olck"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Orkh")
    ORKH("Orkh"),
    @XmlEnumValue("Orya")
    ORYA("Orya"),

    /**
     * For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Osge")
    OSGE("Osge"),
    @XmlEnumValue("Osma")
    OSMA("Osma"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Palm")
    PALM("Palm"),

    /**
     * For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Pauc")
    PAUC("Pauc"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Perm")
    PERM("Perm"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Phag")
    PHAG("Phag"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Phli")
    PHLI("Phli"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Phlp")
    PHLP("Phlp"),

    /**
     * Script is not supported by Unicode
     * 
     */
    @XmlEnumValue("Phlv")
    PHLV("Phlv"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Phnx")
    PHNX("Phnx"),
    @XmlEnumValue("Plrd")
    PLRD("Plrd"),

    /**
     * Script is not supported by Unicode. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Piqd")
    PIQD("Piqd"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Prti")
    PRTI("Prti"),
    @XmlEnumValue("Qaaa")
    QAAA("Qaaa"),
    @XmlEnumValue("Qabx")
    QABX("Qabx"),
    @XmlEnumValue("Rjng")
    RJNG("Rjng"),

    /**
     * Script is not supported by Unicode
     * 
     */
    @XmlEnumValue("Roro")
    RORO("Roro"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Runr")
    RUNR("Runr"),
    @XmlEnumValue("Samr")
    SAMR("Samr"),

    /**
     * Script is not supported by Unicode
     * 
     */
    @XmlEnumValue("Sara")
    SARA("Sara"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Sarb")
    SARB("Sarb"),
    @XmlEnumValue("Saur")
    SAUR("Saur"),
    @XmlEnumValue("Sgnw")
    SGNW("Sgnw"),
    @XmlEnumValue("Shaw")
    SHAW("Shaw"),
    @XmlEnumValue("Shrd")
    SHRD("Shrd"),

    /**
     * Ancient/historic script. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Sidd")
    SIDD("Sidd"),
    @XmlEnumValue("Sind")
    SIND("Sind"),
    @XmlEnumValue("Sinh")
    SINH("Sinh"),
    @XmlEnumValue("Sora")
    SORA("Sora"),

    /**
     * For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Soyo")
    SOYO("Soyo"),
    @XmlEnumValue("Sund")
    SUND("Sund"),
    @XmlEnumValue("Sylo")
    SYLO("Sylo"),
    @XmlEnumValue("Syrc")
    SYRC("Syrc"),

    /**
     * Typographic variant of Syriac
     * 
     */
    @XmlEnumValue("Syre")
    SYRE("Syre"),

    /**
     * Typographic variant of Syriac
     * 
     */
    @XmlEnumValue("Syrj")
    SYRJ("Syrj"),

    /**
     * Typographic variant of Syriac
     * 
     */
    @XmlEnumValue("Syrn")
    SYRN("Syrn"),
    @XmlEnumValue("Tagb")
    TAGB("Tagb"),
    @XmlEnumValue("Takr")
    TAKR("Takr"),
    @XmlEnumValue("Tale")
    TALE("Tale"),
    @XmlEnumValue("Talu")
    TALU("Talu"),
    @XmlEnumValue("Taml")
    TAML("Taml"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Tang")
    TANG("Tang"),
    @XmlEnumValue("Tavt")
    TAVT("Tavt"),
    @XmlEnumValue("Telu")
    TELU("Telu"),

    /**
     * Script is not supported by Unicode
     * 
     */
    @XmlEnumValue("Teng")
    TENG("Teng"),
    @XmlEnumValue("Tfng")
    TFNG("Tfng"),
    @XmlEnumValue("Tglg")
    TGLG("Tglg"),
    @XmlEnumValue("Thaa")
    THAA("Thaa"),
    @XmlEnumValue("Thai")
    THAI("Thai"),
    @XmlEnumValue("Tibt")
    TIBT("Tibt"),
    @XmlEnumValue("Tirh")
    TIRH("Tirh"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Ugar")
    UGAR("Ugar"),
    @XmlEnumValue("Vaii")
    VAII("Vaii"),

    /**
     * Script is not supported by Unicode
     * 
     */
    @XmlEnumValue("Visp")
    VISP("Visp"),
    @XmlEnumValue("Wara")
    WARA("Wara"),

    /**
     * Script is not supported by Unicode
     * 
     */
    @XmlEnumValue("Wole")
    WOLE("Wole"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Xpeo")
    XPEO("Xpeo"),

    /**
     * Ancient/historic script
     * 
     */
    @XmlEnumValue("Xsux")
    XSUX("Xsux"),
    @XmlEnumValue("Yiii")
    YIII("Yiii"),

    /**
     * For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Zanb")
    ZANB("Zanb"),
    @XmlEnumValue("Zinh")
    ZINH("Zinh"),

    /**
     * Not a script in Unicode
     * 
     */
    @XmlEnumValue("Zmth")
    ZMTH("Zmth"),

    /**
     * Not a script in Unicode. For use in ONIX 3.0 only
     * 
     */
    @XmlEnumValue("Zsye")
    ZSYE("Zsye"),

    /**
     * Not a script in Unicode
     * 
     */
    @XmlEnumValue("Zsym")
    ZSYM("Zsym"),

    /**
     * Not a script in Unicode
     * 
     */
    @XmlEnumValue("Zxxx")
    ZXXX("Zxxx"),
    @XmlEnumValue("Zyyy")
    ZYYY("Zyyy"),
    @XmlEnumValue("Zzzz")
    ZZZZ("Zzzz");
    private final String value;

    List121(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static List121 fromValue(String v) {
        for (List121 c: List121 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
