//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 02:03:50 PM GST 
//


package com.maintainapps.schema.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List255.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="List255">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ALP"/>
 *     &lt;enumeration value="APP"/>
 *     &lt;enumeration value="ATC"/>
 *     &lt;enumeration value="AHL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "List255")
@XmlEnum
public enum List255 {


    /**
     * Insert appears after an even numbered or before an odd numbered logical page. <InsertPointValue> is an integer page number
     * 
     */
    ALP,

    /**
     * Insert appears after an even numbered or before an odd numbered printed page number. <InsertPointValue> is an integer page number
     * 
     */
    APP,

    /**
     * Insert appears in the body at a specific timecode (hours, minutes, seconds, counted from the beginning of the product before any inserts are added). <InsertPointValue> is in the format HHHMMSS. Fill with leading zeroes if any elements are missing. If centisecond precision is required, use HHHMMSScc
     * 
     */
    ATC,

    /**
     * Insert appears before the block-level HTML element – &lt;InsertPointValue> is the value of the id or name attribute of the block-level element (which must be unique within the body of the product)
     * 
     */
    AHL;

    public String value() {
        return name();
    }

    public static List255 fromValue(String v) {
        return valueOf(v);
    }

}
