//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 02:03:50 PM GST 
//


package com.maintainapps.schema.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List139.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="List139">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SYM"/>
 *     &lt;enumeration value="ACM"/>
 *     &lt;enumeration value="AAP"/>
 *     &lt;enumeration value="ADL"/>
 *     &lt;enumeration value="ACB"/>
 *     &lt;enumeration value="AKK"/>
 *     &lt;enumeration value="ALB"/>
 *     &lt;enumeration value="ALT"/>
 *     &lt;enumeration value="AMZ"/>
 *     &lt;enumeration value="ANR"/>
 *     &lt;enumeration value="ANB"/>
 *     &lt;enumeration value="APA"/>
 *     &lt;enumeration value="APC"/>
 *     &lt;enumeration value="ASD"/>
 *     &lt;enumeration value="ASB"/>
 *     &lt;enumeration value="AUD"/>
 *     &lt;enumeration value="AUC"/>
 *     &lt;enumeration value="ATK"/>
 *     &lt;enumeration value="BDL"/>
 *     &lt;enumeration value="BNO"/>
 *     &lt;enumeration value="BDZ"/>
 *     &lt;enumeration value="BBB"/>
 *     &lt;enumeration value="BST"/>
 *     &lt;enumeration value="MMM"/>
 *     &lt;enumeration value="BIL"/>
 *     &lt;enumeration value="BLG"/>
 *     &lt;enumeration value="BJW"/>
 *     &lt;enumeration value="BLA"/>
 *     &lt;enumeration value="BLK"/>
 *     &lt;enumeration value="GOS"/>
 *     &lt;enumeration value="BKU"/>
 *     &lt;enumeration value="BLD"/>
 *     &lt;enumeration value="BCA"/>
 *     &lt;enumeration value="BOO"/>
 *     &lt;enumeration value="BSH"/>
 *     &lt;enumeration value="BKP"/>
 *     &lt;enumeration value="BRB"/>
 *     &lt;enumeration value="BKM"/>
 *     &lt;enumeration value="BKS"/>
 *     &lt;enumeration value="BTP"/>
 *     &lt;enumeration value="BKY"/>
 *     &lt;enumeration value="BRD"/>
 *     &lt;enumeration value="BRT"/>
 *     &lt;enumeration value="CDL"/>
 *     &lt;enumeration value="CDN"/>
 *     &lt;enumeration value="CEB"/>
 *     &lt;enumeration value="CHD"/>
 *     &lt;enumeration value="CYM"/>
 *     &lt;enumeration value="CMX"/>
 *     &lt;enumeration value="COP"/>
 *     &lt;enumeration value="CST"/>
 *     &lt;enumeration value="CRB"/>
 *     &lt;enumeration value="CVS"/>
 *     &lt;enumeration value="CVM"/>
 *     &lt;enumeration value="CYB"/>
 *     &lt;enumeration value="DEM"/>
 *     &lt;enumeration value="DSG"/>
 *     &lt;enumeration value="DIL"/>
 *     &lt;enumeration value="DYM"/>
 *     &lt;enumeration value="EPA"/>
 *     &lt;enumeration value="ERD"/>
 *     &lt;enumeration value="ELC"/>
 *     &lt;enumeration value="ESN"/>
 *     &lt;enumeration value="EBC"/>
 *     &lt;enumeration value="ECH"/>
 *     &lt;enumeration value="ECI"/>
 *     &lt;enumeration value="ELE"/>
 *     &lt;enumeration value="ELB"/>
 *     &lt;enumeration value="ELK"/>
 *     &lt;enumeration value="ELS"/>
 *     &lt;enumeration value="ELL"/>
 *     &lt;enumeration value="EMP"/>
 *     &lt;enumeration value="ENH"/>
 *     &lt;enumeration value="EPC"/>
 *     &lt;enumeration value="FDB"/>
 *     &lt;enumeration value="FIN"/>
 *     &lt;enumeration value="FSP"/>
 *     &lt;enumeration value="FLP"/>
 *     &lt;enumeration value="FNC"/>
 *     &lt;enumeration value="FOL"/>
 *     &lt;enumeration value="FRY"/>
 *     &lt;enumeration value="GMS"/>
 *     &lt;enumeration value="GLO"/>
 *     &lt;enumeration value="GOO"/>
 *     &lt;enumeration value="HST"/>
 *     &lt;enumeration value="HMV"/>
 *     &lt;enumeration value="HMD"/>
 *     &lt;enumeration value="IMM"/>
 *     &lt;enumeration value="IND"/>
 *     &lt;enumeration value="IBS"/>
 *     &lt;enumeration value="IZN"/>
 *     &lt;enumeration value="JBH"/>
 *     &lt;enumeration value="JSM"/>
 *     &lt;enumeration value="KMT"/>
 *     &lt;enumeration value="KID"/>
 *     &lt;enumeration value="KPV"/>
 *     &lt;enumeration value="KNB"/>
 *     &lt;enumeration value="KNO"/>
 *     &lt;enumeration value="KBO"/>
 *     &lt;enumeration value="KOO"/>
 *     &lt;enumeration value="KOR"/>
 *     &lt;enumeration value="KRG"/>
 *     &lt;enumeration value="LTP"/>
 *     &lt;enumeration value="LWE"/>
 *     &lt;enumeration value="MAC"/>
 *     &lt;enumeration value="MAG"/>
 *     &lt;enumeration value="MKS"/>
 *     &lt;enumeration value="MAT"/>
 *     &lt;enumeration value="MMS"/>
 *     &lt;enumeration value="ADP"/>
 *     &lt;enumeration value="MCR"/>
 *     &lt;enumeration value="MSF"/>
 *     &lt;enumeration value="MOF"/>
 *     &lt;enumeration value="MRR"/>
 *     &lt;enumeration value="MTC"/>
 *     &lt;enumeration value="MYB"/>
 *     &lt;enumeration value="MYI"/>
 *     &lt;enumeration value="NTR"/>
 *     &lt;enumeration value="NXT"/>
 *     &lt;enumeration value="NUM"/>
 *     &lt;enumeration value="OFD"/>
 *     &lt;enumeration value="OFM"/>
 *     &lt;enumeration value="OLF"/>
 *     &lt;enumeration value="OVD"/>
 *     &lt;enumeration value="OYS"/>
 *     &lt;enumeration value="PST"/>
 *     &lt;enumeration value="PTS"/>
 *     &lt;enumeration value="PTC"/>
 *     &lt;enumeration value="PLY"/>
 *     &lt;enumeration value="POK"/>
 *     &lt;enumeration value="PTB"/>
 *     &lt;enumeration value="RDB"/>
 *     &lt;enumeration value="RCL"/>
 *     &lt;enumeration value="RST"/>
 *     &lt;enumeration value="RET"/>
 *     &lt;enumeration value="RTZ"/>
 *     &lt;enumeration value="RMB"/>
 *     &lt;enumeration value="RBD"/>
 *     &lt;enumeration value="SGR"/>
 *     &lt;enumeration value="SAF"/>
 *     &lt;enumeration value="SFW"/>
 *     &lt;enumeration value="SNS"/>
 *     &lt;enumeration value="SCR"/>
 *     &lt;enumeration value="SLF"/>
 *     &lt;enumeration value="SEQ"/>
 *     &lt;enumeration value="SBT"/>
 *     &lt;enumeration value="SKB"/>
 *     &lt;enumeration value="SMW"/>
 *     &lt;enumeration value="SNY"/>
 *     &lt;enumeration value="STP"/>
 *     &lt;enumeration value="STT"/>
 *     &lt;enumeration value="SKK"/>
 *     &lt;enumeration value="SPL"/>
 *     &lt;enumeration value="SUP"/>
 *     &lt;enumeration value="SSK"/>
 *     &lt;enumeration value="TRG"/>
 *     &lt;enumeration value="TES"/>
 *     &lt;enumeration value="TEA"/>
 *     &lt;enumeration value="TOL"/>
 *     &lt;enumeration value="TSR"/>
 *     &lt;enumeration value="TSO"/>
 *     &lt;enumeration value="TXR"/>
 *     &lt;enumeration value="UBH"/>
 *     &lt;enumeration value="VRG"/>
 *     &lt;enumeration value="WHS"/>
 *     &lt;enumeration value="WTR"/>
 *     &lt;enumeration value="WLM"/>
 *     &lt;enumeration value="WST"/>
 *     &lt;enumeration value="WHT"/>
 *     &lt;enumeration value="WLS"/>
 *     &lt;enumeration value="WLW"/>
 *     &lt;enumeration value="YOU"/>
 *     &lt;enumeration value="ZVV"/>
 *     &lt;enumeration value="PUB"/>
 *     &lt;enumeration value="ZZZ"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "List139")
@XmlEnum
public enum List139 {

    SYM,
    ACM,

    /**
     * Academic and Professional Book Center (HK)
     * 
     */
    AAP,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    ADL,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    ACB,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    AKK,
    ALB,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    ALT,
    AMZ,
    ANR,
    ANB,
    APA,
    APC,
    ASD,
    ASB,
    AUD,
    AUC,
    ATK,

    /**
     * Deprecated
     * 
     */
    BDL,
    BNO,

    /**
     * www.bdbuzz.net, for use in ONIX 3.0 only
     * 
     */
    BDZ,
    BBB,
    BST,

    /**
     * Formerly 3M Cloud Library
     * 
     */
    MMM,

    /**
     * Deprecated
     * 
     */
    BIL,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    BLG,
    BJW,

    /**
     * Deprecated
     * 
     */
    BLA,
    BLK,

    /**
     * Formerly GoSpoken/Mobcast. Deprecated
     * 
     */
    GOS,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    BKU,

    /**
     * www.bolinda.com, for use in ONIX 3.0 only
     * 
     */
    BLD,
    BCA,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    BOO,
    BSH,
    BKP,

    /**
     * Deprecated
     * 
     */
    BRB,
    BKM,
    BKS,
    BTP,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    BKY,

    /**
     * Deprecated
     * 
     */
    BRD,

    /**
     * Deprecated
     * 
     */
    BRT,
    CDL,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    CDN,
    CEB,
    CHD,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    CYM,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    CMX,

    /**
     * Deprecated
     * 
     */
    COP,
    CST,
    CRB,
    CVS,

    /**
     * www.cvs-mediatheques.com
     * 
     */
    CVM,
    CYB,
    DEM,
    DSG,
    DIL,
    DYM,
    EPA,
    ERD,
    ELC,
    ESN,

    /**
     * www.ebooks.com
     * 
     */
    EBC,

    /**
     * Deprecated
     * 
     */
    ECH,
    ECI,
    ELE,
    ELB,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    ELK,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    ELS,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    ELL,
    EMP,
    ENH,

    /**
     * www.getepic.com
     * 
     */
    EPC,
    FDB,
    FIN,
    FSP,
    FLP,
    FNC,
    FOL,
    FRY,
    GMS,
    GLO,
    GOO,

    /**
     * Deprecated
     * 
     */
    HST,
    HMV,
    HMD,
    IMM,
    IND,

    /**
     * www.ibs.it, for use in ONIX 3.0 only
     * 
     */
    IBS,
    IZN,
    JBH,
    JSM,
    KMT,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    KID,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    KPV,
    KNB,

    /**
     * Deprecate
     * 
     */
    KNO,
    KBO,
    KOO,
    KOR,
    KRG,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    LTP,
    LWE,
    MAC,
    MAG,
    MKS,
    MAT,

    /**
     * Also known as Media World
     * 
     */
    MMS,
    ADP,
    MCR,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    MSF,
    MOF,
    MRR,
    MTC,

    /**
     * Deprecated
     * 
     */
    MYB,
    MYI,
    NTR,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    NXT,
    NUM,
    OFD,
    OFM,
    OLF,
    OVD,

    /**
     * Deprecated
     * 
     */
    OYS,

    /**
     * Deprecated
     * 
     */
    PST,
    PTS,
    PTC,
    PLY,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    POK,
    PTB,

    /**
     * Deprecated
     * 
     */
    RDB,
    RCL,
    RST,
    RET,
    RTZ,

    /**
     * Deprecated
     * 
     */
    RMB,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    RBD,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    SGR,
    SAF,
    SFW,
    SNS,
    SCR,
    SLF,
    SEQ,
    SBT,
    SKB,
    SMW,
    SNY,
    STP,
    STT,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    SKK,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    SPL,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    SUP,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    SSK,
    TRG,
    TES,
    TEA,
    TOL,
    TSR,
    TSO,

    /**
     * Deprecated
     * 
     */
    TXR,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    UBH,

    /**
     * Deprecated
     * 
     */
    VRG,
    WHS,
    WTR,
    WLM,
    WST,
    WHT,
    WLS,
    WLW,

    /**
     * youboox.fr
     * 
     */
    YOU,

    /**
     * Formerly Virgin Megastores (UK)
     * 
     */
    ZVV,

    /**
     * For use in ONIX 3.0 only
     * 
     */
    PUB,

    /**
     * Include retailer name in <SalesOutletName>
     * 
     */
    ZZZ;

    public String value() {
        return name();
    }

    public static List139 fromValue(String v) {
        return valueOf(v);
    }

}
