//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 02:03:50 PM GST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ns.editeur.org/onix/3.0/reference", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.maintainapps.schema.xml;
